### ISSUE TITLE
Lookup Flags Extensions: u16 or u32

### ISSUE THREAD

**Issue by behdad** [OpenType/opentype-layout#20]
In reference to:
https://github.com/OpenType/opentype-layout/blob/63d169c92160832cf5b2333f28b559c80c9a4389/proposals/lookupflags_extend.md

Let's resolve the discussion issue there. I'm moving forward to implement this (and then other ones).

> Do we want to extend the ExtraFlags to 32-bits and save a level of future chaining? We are already expecting 4 bits to be used in future proposals.

I can argue both ways, neither very strong, and I see no blocking issue with either. So let's go with the shorter one.

**Comment by mhosken** [comment]
I have no problem with that. Given the speed at which the list will grow, I'm sure we're good for a while yet.

**Comment by behdad** [comment]
Moved to: https://github.com/be-fonts/boring-expansion-spec/issues/26
