### ISSUE TITLE
Glyph Filtering: Clarify a couple things

### ISSUE THREAD

**Issue by behdad** [OpenType/opentype-layout#21]
In reference to:
https://github.com/OpenType/opentype-layout/blob/63d169c92160832cf5b2333f28b559c80c9a4389/proposals/glyph_filtering.md

I like to implement this. As I did back then, I really like the 4 cases you came up with. That's very flexible. Let's address a few issues and I'll proceed to implement in HB:

- This has to be done before the LookupFlag Extension proposal, since MarkFilteringSet member of Lookup table will now also be encoded of the new UseFiltering flag is on.

- Should we rename those fields? Maybe better to combine the two flags into a 2-bit enum. OpenType has done renames before. Mostly a non-issue, except for libraries like fonttools. cc @anthrotype

**Comment by behdad** [comment]
Also, the following line needs further clarification:

> If in addition to UseFiltering any of the IgnoreBaseGlyphs, IgnoreLigatures or IgnoreMarks are set, then all of the corresponding classes of glyphs will be skipped in addition to those specified by UseFiltering.

"...will be skipped in addition to..." isn't accurate, since in two of the modes, UseFiltering specified which glyphs NOT to skip. We should specify whether IgnoreBaseGlyphs and IgnoreLigatures take priority or not. Same about IgnoreMarks, but that one needs even more discussion given the current entanglement with MarkFilteringSet. I haven't fully analyzed the situation.

**Comment by mhosken** [comment]
I would suggest as a starting discussion point that we give the highest priority to the most precisely specified. In this case I would start by making UseFiltering have priority over the use of IgnoreX. Perhaps we should write it in terms of set semantics, listing all the sets involved and how they combine to produce a final set (or negative set) of glyphs to process?

**Comment by behdad** [comment]
When skipping, always skip in addition to "Ignore*". When not skipping, don't skip in spite of "Ignore*".

**Comment by behdad** [comment]
I'm happy with this; Moving on to be-fonts repo to implement.
